// This file is auto-generated by @hey-api/openapi-ts

import { useAuthStore } from "@/data/api/auth/_services_/store";

import { createClient, createConfig } from "./client";

export type ClientOptions2 = {
  baseUrl: string;
};

/** Các route chỉ dùng body/cookie, không gửi Bearer access (tránh token cũ làm hỏng refresh/login). */
const AUTH_NO_BEARER_PATHS = [
  "/api/auth/refresh-token",
  "/api/auth/login",
  "/api/auth/register",
  "/api/auth/verify-email",
] as const;

function authRequestSkipsBearer(url: string): boolean {
  return AUTH_NO_BEARER_PATHS.some((p) => url.includes(p));
}


// Không persist refresh token, nhưng trong 1 session vẫn refresh để giảm 401.
async function refreshToken() {
  try {
    const st = useAuthStore.getState();
    const refreshTokenValue = st.refreshToken;
    if (!refreshTokenValue) {
      return null;
    }

    const response = await fetch(`${import.meta.env.VITE_API_URL}/api/auth/refresh-token`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ refreshToken: refreshTokenValue }),
    });

    if (!response.ok) {
      return null;
    }

    const data = (await response.json()) as any;
    if (data?.accessToken) {
      // race-safe: nếu refreshToken đã đổi giữa chừng, đừng ghi đè
      if (useAuthStore.getState().refreshToken !== refreshTokenValue) {
        return data;
      }
      st.setAccessToken(data.accessToken);
      if (data?.refreshToken) st.setRefreshToken(data.refreshToken);
      if (data?.user) st.setUser(data.user);
      return data;
    }
    return null;
  } catch {
    return null;
  }
}
export const client = createClient(
  createConfig<ClientOptions2>({
    baseUrl: import.meta.env.VITE_API_URL,
  }),
);

client.interceptors.request.use((request) => {
  if (authRequestSkipsBearer(request.url)) {
    return request;
  }
  const accessToken = useAuthStore.getState().accessToken;
  if (!accessToken) {
    return request;
  }
  const headers = new Headers(request.headers);
  if (!headers.has("Authorization")) {
    headers.set("Authorization", `Bearer ${accessToken}`);
  }
  return new Request(request, { headers });
});


let refreshPromise: Promise<any> | null = null;
client.interceptors.response.use(async (response, request: any) => {
  if (response.status !== 401) {
    return response;
  }
  if (request.options?.headers?.['x-retried']) {
    return response;
  }

  if (!refreshPromise) {
    refreshPromise = refreshToken().finally(() => {
      refreshPromise = null;
    });
  }

  const data = await refreshPromise;
  if (!data) {
    useAuthStore.getState().clear();
    return response;
  }

  const retried = await client.request({
    ...request.options,
    headers: {
      ...request.options.headers,
      "x-retried": "1",
    },
  });

  return retried.response;
})