// This file is auto-generated by @hey-api/openapi-ts

import { useAuthStore } from "@/data/api/auth/_services_/store";
import { createClient, createConfig } from "./client";

export type ClientOptions2 = {
  baseUrl: string;
};

export const client = createClient(
  createConfig<ClientOptions2>({
    baseUrl: import.meta.env.VITE_API_URL,
  }),
);

client.interceptors.request.use((request) => {
  const accessToken = useAuthStore.getState().token?.accessToken;
  if (!accessToken) {
    return request;
  }
  const headers = new Headers(request.headers);
  if (!headers.has("Authorization")) {
    headers.set("Authorization", `Bearer ${accessToken}`);
  }
  return new Request(request, { headers });
});

client.interceptors.response.use(async (response, request: any) => {
    if(response.status !== 401){
        return response;
    }
    if(request.options?.headers?.['x-retried']){
        return response;
    }

    const retried = await client.request({
        ...request.options,
        headers: {
          ...request.options.headers,
          "x-retried": "1",
        },
      });
    
      return retried.response;
})